#!/bin/bash
# A wrapper around `aws lambda create-function` to create a new Lambda function

# Exit immediately if a command exits with a non-zero status
set -e

function usage() {
    if [[ $# -eq 0 ]] ; then
        echo "$(basename ${0}) <path>"
        exit 0
    fi
}

function build_package() {
    # Prepare package for deploy
    source=$(mktemp -d)
    dest=$(mktemp -d)

    cp -r "$1" $source
    cd "$source"

    # Include dependencies defined via Pipfile
    if [ -e "Pipfile" ] ; then
        pipenv lock --requirements > requirements.txt
        pip install -r requirements.txt -t .
    fi

    # Generate .zip file, exlude .git, and previous .zip files
    zip -r "${dest}/package.zip" . --exclude *.git* *.zip *.md LICENSE script/ script/* >/dev/null

    # Return path to the .zip
    echo "${dest}/package.zip"
}

function main() {
    # Check usage
    usage "$@"

    path="$1"

    # Build package from path
    package=$( build_package "${path}" )

    cp "$package" .
}

main "$@"
